### ISSUE TITLE
Bug: Vercel 배포시 발생하는 오류에 관한 안내

### ISSUE THREAD

**Issue by starcradle101** [starcradle101/hoonie-log#9]
## 🖨️ Description
현재 Vercel에서 프로젝트 배포시 다음과 같은 오류가 발생하고 있습니다.
```bash
[15:53:03.561] Running build in Washington, D.C., USA (East) – iad1
[15:53:03.787] Cloning github.com/starcradle101/hoonie-log (Branch: main, Commit: af075b6)
[15:53:04.340] Previous build cache not available
[15:53:06.773] Cloning completed: 2.985s
[15:53:07.426] Running "vercel build"
[15:53:08.607] Vercel CLI 34.3.0
[15:53:11.217] Installing dependencies...
[15:53:25.197] npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[15:53:25.744] npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[15:53:25.767] npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[15:53:25.980] npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
[15:53:26.072] npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[15:53:35.743] 
[15:53:35.743] > hoonie-log@0.1.0 prepare
[15:53:35.744] > husky && husky install
[15:53:35.744] 
[15:53:35.875] install command is deprecated
[15:53:35.907] 
[15:53:35.907] added 1099 packages in 24s
[15:53:35.907] 
[15:53:35.907] 384 packages are looking for funding
[15:53:35.908]   run `npm fund` for details
[15:53:35.961] Detected Next.js version: 14.2.3
[15:53:35.970] Detected `package-lock.json` generated by npm 7+
[15:53:35.970] Running "npm run build"
[15:53:36.231] 
[15:53:36.232] > hoonie-log@0.1.0 build
[15:53:36.232] > next build
[15:53:36.232] 
[15:53:36.877] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[15:53:36.877] This information is used to shape Next.js' roadmap and prioritize features.
[15:53:36.878] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[15:53:36.878] https://nextjs.org/telemetry
[15:53:36.878] 
[15:53:36.941]   ▲ Next.js 14.2.3
[15:53:36.942] 
[15:53:37.013]    Creating an optimized production build ...
[15:54:07.885]  ✓ Compiled successfully
[15:54:07.886]    Linting and checking validity of types ...
[15:54:11.392] 
[15:54:11.392] ./src/app/components/Toolbar.tsx
[15:54:11.392] 88:3  Warning: React Hook useCallback has an unnecessary dependency: 'editor'. Either exclude it or remove the dependency array.  react-hooks/exhaustive-deps
[15:54:11.392] 
[15:54:11.392] info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[15:54:14.615]    Collecting page data ...
[15:54:16.333]    Generating static pages (0/9) ...
[15:54:16.494]    Generating static pages (2/9) 
[15:54:16.748]  ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/blog". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
[15:54:16.749]     at a (/vercel/path0/.next/server/chunks/819.js:1:10496)
[15:54:16.749]     at s (/vercel/path0/.next/server/chunks/819.js:1:21493)
[15:54:16.749]     at m (/vercel/path0/.next/server/app/(dashboard)/dashboard/posts/page.js:11:1378)
[15:54:16.750]     at nj (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[15:54:16.750]     at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[15:54:16.752]     at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[15:54:16.752]     at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[15:54:16.752]     at nB (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
[15:54:16.752]     at nD (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
[15:54:16.753]     at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
[15:54:16.753] 
[15:54:16.753] Error occurred prerendering page "/blog". Read more: https://nextjs.org/docs/messages/prerender-error
[15:54:16.753] 
[15:54:16.761]    Generating static pages (4/9) 
[15:54:17.361]  ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/dashboard/posts". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
[15:54:17.361]     at a (/vercel/path0/.next/server/chunks/819.js:1:10496)
[15:54:17.361]     at s (/vercel/path0/.next/server/chunks/819.js:1:21493)
[15:54:17.361]     at l (/vercel/path0/.next/server/app/(dashboard)/dashboard/posts/page.js:11:2575)
[15:54:17.361]     at nj (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[15:54:17.361]     at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[15:54:17.361]     at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[15:54:17.361]     at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[15:54:17.362]     at nB (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
[15:54:17.362]     at nD (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
[15:54:17.362]     at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
[15:54:17.362] 
[15:54:17.362] Error occurred prerendering page "/dashboard/posts". Read more: https://nextjs.org/docs/messages/prerender-error
[15:54:17.362] 
[15:54:17.363]    Generating static pages (6/9) 
[15:54:17.471] { title: '', description: '', content: {} }
[15:54:17.696]  ✓ Generating static pages (9/9)
[15:54:17.703] 
[15:54:17.704] > Export encountered errors on following paths:
[15:54:17.704] 	/(blog)/blog/page: /blog
[15:54:17.704] 	/(dashboard)/dashboard/posts/page: /dashboard/posts
[15:54:17.735] Error: Command "npm run build" exited with 1
[15:54:18.110] 
```

기존의 로컬 폴더에서 마크다운 파일을 읽어오는 로직을 `generateStatcParams()`내부에서 적용하고 있었으나, 현재 Supabase를 사용한 CRUD 기능을 구현하기 위해 임시로 삭제한 것으로 인해 발생한 문제로 보입니다. 현 문제에 대해서 기존 로직을 복구하는 것 보다는 배포 환경이 아닌 개발 환경에서는 문제가 되지 않으므로 CRUD 기능 우선적으로 개발 후 해당 부분을 수정하는 것으로 진행하겠습니다.

## 📝 To-do
- [x] Supabase를 사용한 CRUD 기능 구현
- [x] `generateStaticParams()`부분을 교체

## 🧑🏻‍💻 ETC
- 기타 사항은 추후 추가 예정입니다.

**Comment by starcradle101** [comment]
이슈 해결되어 close 합니다. 해당 이슈 관련 내용은 #11 에서 확인할 수 있습니다.
